### ISSUE TITLE
SkipThrottle decorator no longer working

### ISSUE THREAD

**Issue by cnorthfield** [nestjs/throttler#1729] opened 2023-10-22 13:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Using the `SkipThrottle` decorator does not skip throttling.

### Minimum reproduction code

https://gist.github.com/cnorthfield/d7fec118cac6af66d0c03cc1547a79d3

### Steps to reproduce

Add `@SkipThrottle()` decorator to a controller or route.

```typescript
import { Controller, Get } from '@nestjs/common';
import { SkipThrottle } from '@nestjs/throttler';

@Controller('health')
export class HealthController {
  @SkipThrottle()
  @Get()
  getHealth(): string {
    return 'Healthy';
  }
}
```

It also does not work when passing keys i.e:
```typescript
import { Controller, Get } from '@nestjs/common';
import { SkipThrottle } from '@nestjs/throttler';

@Controller('health')
export class HealthController {
  @Get()
  @SkipThrottle({
    short: true,
    medium: true,
    long: true,
  })
  getHealth(): string {
    return 'Healthy';
  }
}

Make a `GET` request to the `/health` endpoint and the following response is returned:

```
{"statusCode":429,"message":"ThrottlerException: Too Many Requests"}
```

```

### Expected behavior

Route is skipped from throttling.

### Package version

5.0.0

### NestJS version

9.0.0

### Node.js version

16.20.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by jmcdo29** [comment] 2023-10-22 14:22
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by micalevisk** [comment] 2023-10-22 14:33
we have a test suite for that

https://github.com/nestjs/throttler/blob/e1882bfea19460e97093b5493cf893fb212773ec/test/app/controllers/app.controller.ts#L15-L19
https://github.com/nestjs/throttler/blob/e1882bfea19460e97093b5493cf893fb212773ec/test/controller.e2e-spec.ts#L47-L54

**Comment by cnorthfield** [comment] 2023-10-23 07:18
Here is a [minimum reproduction repository](https://minimum-reproduction.wtf/):

https://github.com/cnorthfield/nestjs-throttler-issue

# Setup

1) git clone https://github.com/cnorthfield/nestjs-throttler-issue.git
2) cd nestjs-throttler-issue
3) yarn install

# Reproduction

1) yarn start:dev
2) open a browser and navigate to http://localhost:3000
3) refresh the page more than 10 times in 10 seconds
4) see the response `{"statusCode":429,"message":"ThrottlerException: Too Many Requests"}`

The `x-ratelimit-*` headers are present in each response.

**Comment by cnorthfield** [comment] 2023-10-23 07:23
The issue appears when passing `throttlers` to the `ThrottlerModuleOptions` or `ThrottlerAsyncOptions` via `ThrottlerModule.forRoot` and `ThrottlerModule.forRootAsync` respectively and providing `ThrottlerGuard` as an `APP_GUARD`. This does not appear to be covered by tests.

**Comment by jmcdo29** [comment] 2023-10-23 17:09
Awesome, thank you for the reproduction. I'll look into what caused the issue and get a fix released for it

**Comment by jmcdo29** [comment] 2023-10-23 17:15
@cnorthfield #1733 should contain a fix for this. If micalevisk is happy with the changes to the test and decorator I'll merge it (don't wanna just merge it without other eyes :wink:)

**Closed** 2023-10-23 17:59 UTC
Labels: bug

**Comment by LGDHuaOPER** [comment] 2024-08-23 16:05
The problem still exists.

**Comment by jmcdo29** [comment] 2024-08-23 16:07
@LGDHuaOPER Please open a new issue with a minimum reproduction repository. It has been 10 months since this was closed and no one else has reported any issue with it
